birthday1 = input("When is your birthday, John?")
print(f"Your birthday is on {birthday1}, John.")
birthday2 = input("When is your  birthday, Ben?")
print(f"Ben's birthday is on {birthday2}")
birthday3 = input("When is your  birthday, Steve?")
print(f"Steve's birthday is on {birthday3}")
birthday4 = input("When is your birthday, Lucas?")
print(f"Lucas's birthday is on {birthday4}")
birthday5 = input(f"When is your birhday, Micheal?")
print(f"Micheal's birthday is on {birthday5}")
print(f"Raj now knows that John's birthday is on {birthday1}!")
print(f"Raj now knows that Ben's birthday is on {birthday2}!")
print(f"Raj now knows that Steve's birthday is on {birthday3}!")
print(f"Raj now knows that Lucas's birthday is on {birthday4}!")
print(f"Raj now knows that Micheal's birthday is on {birthday5}!")